#!/usr/bin/env sh
LOG_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/../log
sudo NODE_ENV=production forever start -c coffee -a -l forever.log -o "$LOG_DIR"/output.log -e "$LOG_DIR"/error.log app.coffee
